import { Saira_Stencil_One, Bebas_Neue, Lexend_Deca } from "next/font/google";
import Navbar from "@/components/nav/Navbar";
import Footer from "@/components/footer/Footer";
import "./globals.css";

const lexend = Lexend_Deca({
    subsets: ["latin"],
    weight: ["100", "300", "400", "500", "700", "900"],
    display: "swap",
    variable: "--font-lexend"
});
const saira = Saira_Stencil_One({
    subsets: ["latin"],
    weight: ["400"],
    display: 'swap',
    variable: "--font-saira",
});
const bebas = Bebas_Neue({
    subsets: ["latin"],
    weight: ["400"],
    display: 'swap',
    variable: "--font-bebas",
});

export const metadata = {
    title: "Mecha Mayhem | Canada's Largest Robotics Competition",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${lexend.variable} ${saira.variable} ${bebas.variable} tracking-tight bg-black hide-scrollbar text-white w-[100vw] overflow-x-hidden`}
            >
                <Navbar />
                {children}
                {/* <Footer /> */}
            </body>
        </html>
    );
}
